<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
    <xsl:output xml:space="preserve" indent="yes" method="xml"/>
    <xsl:preserve-space elements="*"/>
    <xsl:template match="web-app" xml:space="preserve">
    <web-app version="2.4"
             xmlns="http://java.sun.com/xml/ns/j2ee"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://java.sun.com/xml/ns/j2ee http://java.sun.com/xml/ns/j2ee/web-app_2_4.xsd">

      <xsl:copy-of select="display-name"/>

      <xsl:copy-of select="context-param"/>

      <xsl:copy-of select="filter"/>

      <xsl:copy-of select="filter-mapping[filter-name = 'http-request-context']"/>
      <xsl:copy-of select="filter-mapping[filter-name = 'wadl-filter']"/>

      <!-- instead of copying the filter-mappings generated by enunciate (which use url-mappings), setup filters to
       use <servlet-name>jersey</servlet-name> instead. Due to using wildcards in the url-mappings, a single request
       could have the same filters mapped into the filter chain multiple times. -->
      <xsl:for-each select="filter[starts-with(filter-class, 'org.familysearch')]">
        <filter-mapping>
          <xsl:copy-of select="filter-name"/>
          <servlet-name>jersey</servlet-name>
        </filter-mapping>
      </xsl:for-each>

      <xsl:copy-of select="listener"/>

      <xsl:copy-of select="servlet"/>

      <xsl:copy-of select="servlet-mapping"/>

      <xsl:copy-of select="mime-mapping"/>
    </web-app>

  </xsl:template>

</xsl:stylesheet>
